### ISSUE TITLE
Disconnected users from a room are frozen on remaining users' screens

### ISSUE THREAD

**Issue by ntgomes** [ntgomes/spark#7]
## Summary
When a user in a multi-user room disconnects, the video for that user does not disappear, but instead stays frozen for the rest of the users.

## Steps to reproduce

1. Start the server.
2. Go to a room with multiple users (i.e. multiple tabs in the same URL)
3. Make sure video is shown across all tabs/each user in the room
4. Disconnect from the room by closing the tab.
5. Other people can see that your video is frozen and did not disappear after you left.

## Expected correct behavior

Video should disappear after you leave.

#### Desktop:
 - OS: Windows at least, probably on Mac too
 - Browser: Chrome-based browsers, maybe other browsers

**Comment by ntgomes** [comment]
Partially fixed by #18 ... this may be due to performance issue on the user side. Not much we can do about that unless we find significant ways to reduce overhead.

**Comment by AbhimanyuBellam** [comment]
Yes. Agreed

**Comment by ntgomes** [comment]
@AbhimanyuBellam Once #23 is closed, I would check this again while gestures are turned off by default.
